### ISSUE TITLE
stacking guns error

### ISSUE THREAD

**Issue by olajmuvek** [AnExiledDev/StackSizeController#6]
With this option :  AllowStackingItemsWithDurability = false;

The fullHP of gun stack to a lowe HP gun, after stacking the stacked guns all of have a lower hp. 

if i try to stacking guns with different durability i give this error: 

Failed to call hook 'CanStackItem' on plugin 'StackSizeController v3.3.0' (NullReferenceException: Object reference not set to an instance of an object)
  at Oxide.Plugins.StackSizeController.CanStackItem (Item item, Item targetItem) [0x002a5] in <650494faced74fbb9823a90d4f550ca5>:0 
  at Oxide.Plugins.StackSizeController.DirectCallHook (System.String name, System.Object& ret, System.Object[] args) [0x00e7b] in <650494faced74fbb9823a90d4f550ca5>:0 
  at Oxide.Plugins.CSharpPlugin.InvokeMethod (Oxide.Core.Plugins.HookMethod method, System.Object[] args) [0x00079] in <3606d2af539c45e4b5c61658e6a8b307>:0 
  at Oxide.Core.Plugins.CSPlugin.OnCallHook (System.String name, System.Object[] args) [0x000d8] in <c2afd8354b8b4f3ca451cf5a1aa111c3>:0 
  at Oxide.Core.Plugins.Plugin.CallHook (System.String hook, System.Object[] args) [0x00060] in <c2afd8354b8b4f3ca451cf5a1aa111c3>:0

**Comment by olajmuvek** [comment]
If i have stacked new guns (100% of durability) on the backpack, and on my hand have one of for example 60% durability of gun.
When i right click on the backpack to the new stacked guns, all of guns have 60% durability in my hand. That's the error
I tried with this option too:
"AllowStackingItemsWithDurability": false,

**Comment by AnExiledDev** [comment]
Does this happen outside of backpacks? Like in a normal storage container? Mind telling me what other plugins you have, often times it's plugin conflicts.

**Comment by olajmuvek** [comment]
i removed every plugin. On oxide plugins directory only have your StackSizeController 3.3.0 version. The problem is also have with stacking guns with durability.
I think it's not a plugin conlict, any other idea? please test it you too. The trouble is also working on large box not only backpacks. 
thanks

**Comment by AnExiledDev** [comment]
Try this version and let me know if it solves any issues, and especially if it creates any new issues https://raw.githubusercontent.com/AnExiledDev/StackSizeController/pookins_test/StackSizeController.cs

**Comment by olajmuvek** [comment]
i also test with this version because i need the no skin stack option.
I wrote i try to use this this pookins_test 3.3.0 version
I think the problem is over line 650

I am trying to resolve problem.... I thinks this modification is better works, but i don't want to send a commit please check it out :

                 (item.IsBlueprint() && item.blueprintTarget != targetItem.blueprintTarget) ||
                 (_config.PreventStackingDifferentSkins && item.skin != targetItem.skin) ||
                 (item.hasCondition && (item.condition != item.info.condition.max || 
                 targetItem.condition != targetItem.info.condition.max))

**Comment by olajmuvek** [comment]
but now if i stacking guns, and firing with it, the durability have all of stacked guns... how can repair this trouble ?

**Comment by olajmuvek** [comment]
and all of gears like all stacked metal chest plate loose durability

**Comment by olajmuvek** [comment]
released a new version of plugin.
